# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'robot_gui_test4.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 480)
        MainWindow.setStyleSheet("/* Main application background - lighter version */\n"
"QWidget {\n"
"    background-color: #E0F7FA;  /* very light bluish background */\n"
"}\n"
"\n"
"/* Buttons */\n"
"QPushButton {\n"
"    background-color: #00C9A7;  /* bluish-green */\n"
"    color: #FFFFFF;  /* white text */\n"
"    border: 2px solid #008B74;  /* darker border */\n"
"    border-radius: 8px;\n"
"    padding: 8px 16px;\n"
"    font-size: 14px;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #00E6D3;  /* lighter bluish-green */\n"
"    border-color: #00C9A7;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #008B74;  /* darker bluish-green */\n"
"}\n"
"\n"
"/* Labels */\n"
"QLabel {\n"
"    color: #00796B;  /* darker bluish-green for better contrast */\n"
"    font-size: 14px;\n"
"}\n"
"\n"
"QLabel:hover {\n"
"    color: #00C9A7;  /* standard bluish-green */\n"
"}\n"
"\n"
"/* Line edits */\n"
"QLineEdit {\n"
"    background-color: #FFFFFF;  /* white background */\n"
"    color: #00796B;  /* darker bluish-green */\n"
"    border: 1px solid #00C9A7;\n"
"    border-radius: 4px;\n"
"    padding: 5px;\n"
"    selection-background-color: #00C9A7;\n"
"    selection-color: #FFFFFF;\n"
"}\n"
"\n"
"/* Checkboxes and radio buttons */\n"
"QCheckBox, QRadioButton {\n"
"    color: #00796B;\n"
"    spacing: 5px;\n"
"}\n"
"\n"
"QCheckBox::indicator, QRadioButton::indicator {\n"
"    width: 16px;\n"
"    height: 16px;\n"
"    border: 1px solid #00C9A7;\n"
"}\n"
"\n"
"QCheckBox::indicator:checked, QRadioButton::indicator:checked {\n"
"    background-color: #00C9A7;\n"
"    border: 1px solid #008B74;\n"
"}\n"
"\n"
"/* Scrollbars */\n"
"QScrollBar:vertical {\n"
"    background: #B2EBF2;  /* very light blue */\n"
"    width: 12px;\n"
"}\n"
"\n"
"QScrollBar::handle:vertical {\n"
"    background: #00C9A7;\n"
"    min-height: 20px;\n"
"    border-radius: 6px;\n"
"}\n"
"\n"
"QScrollBar::add-line:vertical, QScrollBar::sub-line:vertical {\n"
"    background: none;\n"
"}\n"
"\n"
"/* Progress bar */\n"
"QProgressBar {\n"
"    border: 1px solid #00C9A7;\n"
"    border-radius: 5px;\n"
"    text-align: center;\n"
"    color: #00796B;\n"
"    background: #FFFFFF;\n"
"}\n"
"\n"
"QProgressBar::chunk {\n"
"    background-color: #00C9A7;\n"
"}\n"
"\n"
"/* Combo box */\n"
"QComboBox {\n"
"    background-color: #FFFFFF;\n"
"    color: #00796B;\n"
"    border: 1px solid #00C9A7;\n"
"    border-radius: 4px;\n"
"    padding: 5px;\n"
"}\n"
"\n"
"QComboBox:hover {\n"
"    border: 1px solid #00E6D3;\n"
"}\n"
"\n"
"QComboBox::drop-down {\n"
"    subcontrol-origin: padding;\n"
"    subcontrol-position: top right;\n"
"    width: 20px;\n"
"    border-left-width: 1px;\n"
"    border-left-color: #00C9A7;\n"
"    border-left-style: solid;\n"
"}\n"
"\n"
"/* Sliders */\n"
"QSlider::groove:horizontal {\n"
"    height: 8px;\n"
"    background: #B2EBF2;\n"
"    border-radius: 4px;\n"
"}\n"
"\n"
"QSlider::handle:horizontal {\n"
"    background: #00C9A7;\n"
"    border: 1px solid #008B74;\n"
"    width: 16px;\n"
"    margin: -4px 0;\n"
"    border-radius: 8px;\n"
"}\n"
"\n"
"/* Tab widget */\n"
"QTabWidget::pane {\n"
"    border: 1px solid #00C9A7;\n"
"    background: #FFFFFF;\n"
"}\n"
"\n"
"QTabBar::tab {\n"
"    background: #B2EBF2;\n"
"    color: #00796B;\n"
"    padding: 8px;\n"
"    border: 1px solid #00C9A7;\n"
"    border-bottom: none;\n"
"}\n"
"\n"
"QTabBar::tab:selected {\n"
"    background: #FFFFFF;\n"
"    color: #00C9A7;\n"
"    border-bottom: 1px solid #FFFFFF;\n"
"}\n"
"\n"
"/* Group boxes */\n"
"QGroupBox {\n"
"    border: 1px solid #00C9A7;\n"
"    border-radius: 5px;\n"
"    margin-top: 1ex;\n"
"    color: #00796B;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QGroupBox::title {\n"
"    subcontrol-origin: margin;\n"
"    left: 10px;\n"
"    padding: 0 3px;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.mainstack = QtWidgets.QStackedWidget(self.centralwidget)
        self.mainstack.setGeometry(QtCore.QRect(40, 120, 701, 241))
        self.mainstack.setStyleSheet("")
        self.mainstack.setObjectName("mainstack")
        self.HomePage = QtWidgets.QWidget()
        self.HomePage.setObjectName("HomePage")
        self.label_2 = QtWidgets.QLabel(self.HomePage)
        self.label_2.setGeometry(QtCore.QRect(120, 50, 451, 101))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("\n"
"QLabel {\n"
"    color: #FF9A8B;\n"
"    font-size: 80px;\n"
"    qproperty-alignment: \'AlignCenter\';\n"
"    \n"
"}\n"
"\n"
"QLabel::hover {\n"
"    color: #FF6B95;\n"
"    transition: color 1000ms ease-in-out;\n"
"}")
        self.label_2.setTextFormat(QtCore.Qt.MarkdownText)
        self.label_2.setObjectName("label_2")
        self.mainstack.addWidget(self.HomePage)
        self.CrowdNav = QtWidgets.QWidget()
        self.CrowdNav.setObjectName("CrowdNav")
        self.btn_crwnav_run = QtWidgets.QPushButton(self.CrowdNav)
        self.btn_crwnav_run.setGeometry(QtCore.QRect(260, 10, 130, 41))
        self.btn_crwnav_run.setObjectName("btn_crwnav_run")
        self.crwnav_goal_input = QtWidgets.QTextEdit(self.CrowdNav)
        self.crwnav_goal_input.setGeometry(QtCore.QRect(10, 10, 211, 51))
        self.crwnav_goal_input.setStyleSheet("background-color: #F8F9FA;  /* Light Gray */\n"
"    color: #333333;  /* Dark Gray Text */\n"
"    font-size: 16px;\n"
"    padding: 8px;\n"
"    border: 2px solid #CCCCCC;  /* Light Border */\n"
"    border-radius: 6px;\n"
"    outline: none;")
        self.crwnav_goal_input.setObjectName("crwnav_goal_input")
        self.mainstack.addWidget(self.CrowdNav)
        self.Multifloor = QtWidgets.QWidget()
        self.Multifloor.setObjectName("Multifloor")
        self.frame = QtWidgets.QFrame(self.Multifloor)
        self.frame.setGeometry(QtCore.QRect(0, 160, 701, 71))
        self.frame.setMaximumSize(QtCore.QSize(16777215, 80))
        self.frame.setStyleSheet("")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.btn_flr_G = QtWidgets.QPushButton(self.frame)
        self.btn_flr_G.setStyleSheet("QPushButton {\n"
"    background-color: #B8E0D2;  /* Light Mint Green */\n"
"    color: #2E3440;\n"
"    font-size: 16px;\n"
"    padding: 8px 12px;\n"
"    border-radius: 8px;\n"
"    border: 2px solid #90C9B7;\n"
"    transition: 0.3s;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #90C9B7;\n"
"    border: 2px solid #6CA893;\n"
"}\n"
"")
        self.btn_flr_G.setObjectName("btn_flr_G")
        self.horizontalLayout_4.addWidget(self.btn_flr_G)
        self.btn_flr_1 = QtWidgets.QPushButton(self.frame)
        self.btn_flr_1.setStyleSheet("QPushButton {\n"
"    background-color: #B8E0D2;  /* Light Mint Green */\n"
"    color: #2E3440;\n"
"    font-size: 16px;\n"
"    padding: 8px 12px;\n"
"    border-radius: 8px;\n"
"    border: 2px solid #90C9B7;\n"
"    transition: 0.3s;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #90C9B7;\n"
"    border: 2px solid #6CA893;\n"
"}\n"
"")
        self.btn_flr_1.setObjectName("btn_flr_1")
        self.horizontalLayout_4.addWidget(self.btn_flr_1)
        self.btn_flr_2 = QtWidgets.QPushButton(self.frame)
        self.btn_flr_2.setStyleSheet("QPushButton {\n"
"    background-color: #B8E0D2;  /* Light Mint Green */\n"
"    color: #2E3440;\n"
"    font-size: 16px;\n"
"    padding: 8px 12px;\n"
"    border-radius: 8px;\n"
"    border: 2px solid #90C9B7;\n"
"    transition: 0.3s;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #90C9B7;\n"
"    border: 2px solid #6CA893;\n"
"}\n"
"")
        self.btn_flr_2.setObjectName("btn_flr_2")
        self.horizontalLayout_4.addWidget(self.btn_flr_2)
        self.btn_flr_3 = QtWidgets.QPushButton(self.frame)
        self.btn_flr_3.setStyleSheet("QPushButton {\n"
"    background-color: #B8E0D2;  /* Light Mint Green */\n"
"    color: #2E3440;\n"
"    font-size: 16px;\n"
"    padding: 8px 12px;\n"
"    border-radius: 8px;\n"
"    border: 2px solid #90C9B7;\n"
"    transition: 0.3s;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #90C9B7;\n"
"    border: 2px solid #6CA893;\n"
"}\n"
"")
        self.btn_flr_3.setObjectName("btn_flr_3")
        self.horizontalLayout_4.addWidget(self.btn_flr_3)
        self.floorStack = QtWidgets.QStackedWidget(self.Multifloor)
        self.floorStack.setGeometry(QtCore.QRect(0, 60, 701, 91))
        self.floorStack.setMaximumSize(QtCore.QSize(16777211, 100))
        self.floorStack.setStyleSheet("/* ---------------------------- */\n"
"/* Frame style (transparent glass) */\n"
"/* ---------------------------- */\n"
"QFrame {\n"
"    background-color: rgba(255, 255, 255, 0.85);\n"
"    border: 1px solid rgba(0, 201, 167, 0.3);\n"
"    border-radius: 12px;\n"
"    padding: 16px;\n"
"    backdrop-filter: blur(8px);\n"
"}\n"
"\n"
"/* ---------------------------- */\n"
"/* Buttons inside the frame */\n"
"/* ---------------------------- */\n"
"QFrame QPushButton {\n"
"    background-color: rgba(0, 201, 167, 0.7);\n"
"    color: white;\n"
"    border: none;\n"
"    border-radius: 6px;\n"
"    padding: 8px 16px;\n"
"    font-weight: 500;\n"
"    min-width: 90px;\n"
"}\n"
"\n"
"QFrame QPushButton:hover {\n"
"    background-color: rgba(0, 201, 167, 0.9);\n"
"}\n"
"\n"
"QFrame QPushButton:pressed {\n"
"    background-color: rgba(0, 155, 130, 0.9);\n"
"}\n"
"\n"
"/* ---------------------------- */\n"
"/* Labels inside the frame */\n"
"/* ---------------------------- */\n"
"QFrame QLabel {\n"
"    color: #00695C;\n"
"    font-size: 14px;\n"
"    font-weight: 500;\n"
"}\n"
"\n"
"QFrame QLabel#title {  /* For labels with objectName=\"title\" */\n"
"    font-size: 18px;\n"
"    font-weight: 600;\n"
"    color: #00A8A8;\n"
"}\n"
"\n"
"/* ---------------------------- */\n"
"/* Input fields in the frame */\n"
"/* ---------------------------- */\n"
"QFrame QLineEdit, QFrame QTextEdit {\n"
"    background-color: white;\n"
"    border: 1px solid rgba(0, 201, 167, 0.5);\n"
"    border-radius: 6px;\n"
"    padding: 8px;\n"
"    selection-background-color: #00C9A7;\n"
"}\n"
"\n"
"QFrame QLineEdit:focus, QFrame QTextEdit:focus {\n"
"    border: 1px solid #00C9A7;\n"
"}\n"
"\n"
"/* ---------------------------- */\n"
"/* Checkboxes/Radio buttons */\n"
"/* ---------------------------- */\n"
"QFrame QCheckBox, QFrame QRadioButton {\n"
"    color: #00695C;\n"
"    spacing: 8px;\n"
"}\n"
"\n"
"QFrame QCheckBox::indicator, QFrame QRadioButton::indicator {\n"
"    width: 18px;\n"
"    height: 18px;\n"
"    border: 1px solid #00C9A7;\n"
"    border-radius: 4px;\n"
"}\n"
"\n"
"QFrame QCheckBox::indicator:checked, QFrame QRadioButton::indicator:checked {\n"
"    background-color: #00C9A7;\n"
"}")
        self.floorStack.setObjectName("floorStack")
        self.pg_flr_G = QtWidgets.QWidget()
        self.pg_flr_G.setObjectName("pg_flr_G")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.pg_flr_G)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btn_reception = QtWidgets.QPushButton(self.pg_flr_G)
        self.btn_reception.setObjectName("btn_reception")
        self.horizontalLayout.addWidget(self.btn_reception)
        self.btn_entc1 = QtWidgets.QPushButton(self.pg_flr_G)
        self.btn_entc1.setObjectName("btn_entc1")
        self.horizontalLayout.addWidget(self.btn_entc1)
        self.btn_uav = QtWidgets.QPushButton(self.pg_flr_G)
        self.btn_uav.setObjectName("btn_uav")
        self.horizontalLayout.addWidget(self.btn_uav)
        self.floorStack.addWidget(self.pg_flr_G)
        self.pg_flr_1 = QtWidgets.QWidget()
        self.pg_flr_1.setObjectName("pg_flr_1")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.pg_flr_1)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.btn_com_lab = QtWidgets.QPushButton(self.pg_flr_1)
        self.btn_com_lab.setObjectName("btn_com_lab")
        self.horizontalLayout_2.addWidget(self.btn_com_lab)
        self.btn_office = QtWidgets.QPushButton(self.pg_flr_1)
        self.btn_office.setObjectName("btn_office")
        self.horizontalLayout_2.addWidget(self.btn_office)
        self.btn_conference = QtWidgets.QPushButton(self.pg_flr_1)
        self.btn_conference.setObjectName("btn_conference")
        self.horizontalLayout_2.addWidget(self.btn_conference)
        self.floorStack.addWidget(self.pg_flr_1)
        self.pg_flr_2 = QtWidgets.QWidget()
        self.pg_flr_2.setObjectName("pg_flr_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.pg_flr_2)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.btn_digi_lab = QtWidgets.QPushButton(self.pg_flr_2)
        self.btn_digi_lab.setObjectName("btn_digi_lab")
        self.horizontalLayout_3.addWidget(self.btn_digi_lab)
        self.btn_analog_lab = QtWidgets.QPushButton(self.pg_flr_2)
        self.btn_analog_lab.setObjectName("btn_analog_lab")
        self.horizontalLayout_3.addWidget(self.btn_analog_lab)
        self.floorStack.addWidget(self.pg_flr_2)
        self.pg_flr_3 = QtWidgets.QWidget()
        self.pg_flr_3.setObjectName("pg_flr_3")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.pg_flr_3)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.btn_pg_room = QtWidgets.QPushButton(self.pg_flr_3)
        self.btn_pg_room.setStyleSheet("QLabel {\n"
"    color: #FF9A8B;\n"
"    qproperty-alignment: \'AlignCenter\';\n"
"}\n"
"\n"
"QLabel::hover {\n"
"    color: #FF6B95;\n"
"    transition: color 1000ms ease-in-out;\n"
"}")
        self.btn_pg_room.setObjectName("btn_pg_room")
        self.horizontalLayout_5.addWidget(self.btn_pg_room)
        self.btn_tele_lab = QtWidgets.QPushButton(self.pg_flr_3)
        self.btn_tele_lab.setStyleSheet("QLabel {\n"
"    color: #FF9A8B;\n"
"    qproperty-alignment: \'AlignCenter\';\n"
"}\n"
"\n"
"QLabel::hover {\n"
"    color: #FF6B95;\n"
"    transition: color 1000ms ease-in-out;\n"
"}")
        self.btn_tele_lab.setObjectName("btn_tele_lab")
        self.horizontalLayout_5.addWidget(self.btn_tele_lab)
        self.floorStack.addWidget(self.pg_flr_3)
        self.Notifications_2 = QtWidgets.QLabel(self.Multifloor)
        self.Notifications_2.setGeometry(QtCore.QRect(20, 20, 691, 31))
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.Notifications_2.setFont(font)
        self.Notifications_2.setWordWrap(True)
        self.Notifications_2.setObjectName("Notifications_2")
        self.mainstack.addWidget(self.Multifloor)
        self.Arm = QtWidgets.QWidget()
        self.Arm.setObjectName("Arm")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.Arm)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.btn_ayubowan = QtWidgets.QPushButton(self.Arm)
        self.btn_ayubowan.setStyleSheet("QPushButton {\n"
"    background-color: #B8E0D2;  /* Light Mint Green */\n"
"    color: #2E3440;\n"
"    font-size: 16px;\n"
"    padding: 8px 12px;\n"
"    border-radius: 8px;\n"
"    border: 2px solid #90C9B7;\n"
"    transition: 0.3s;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #90C9B7;\n"
"    border: 2px solid #6CA893;\n"
"}\n"
"")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("/home/nisala/mobile_robot_ws/src/smrr_gui/smrr_gui/GUIs/Icons/aybowan.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_ayubowan.setIcon(icon)
        self.btn_ayubowan.setIconSize(QtCore.QSize(35, 35))
        self.btn_ayubowan.setObjectName("btn_ayubowan")
        self.horizontalLayout_7.addWidget(self.btn_ayubowan)
        self.btn_hi = QtWidgets.QPushButton(self.Arm)
        self.btn_hi.setStyleSheet("QPushButton {\n"
"    background-color: #B8E0D2;  /* Light Mint Green */\n"
"    color: #2E3440;\n"
"    font-size: 16px;\n"
"    padding: 8px 12px;\n"
"    border-radius: 8px;\n"
"    border: 2px solid #90C9B7;\n"
"    transition: 0.3s;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #90C9B7;\n"
"    border: 2px solid #6CA893;\n"
"}\n"
"")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("/home/nisala/mobile_robot_ws/src/smrr_gui/smrr_gui/GUIs/Icons/Hi.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_hi.setIcon(icon1)
        self.btn_hi.setIconSize(QtCore.QSize(35, 35))
        self.btn_hi.setObjectName("btn_hi")
        self.horizontalLayout_7.addWidget(self.btn_hi)
        self.btn_highfive = QtWidgets.QPushButton(self.Arm)
        self.btn_highfive.setStyleSheet("QPushButton {\n"
"    background-color: #B8E0D2;  /* Light Mint Green */\n"
"    color: #2E3440;\n"
"    font-size: 16px;\n"
"    padding: 8px 12px;\n"
"    border-radius: 8px;\n"
"    border: 2px solid #90C9B7;\n"
"    transition: 0.3s;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #90C9B7;\n"
"    border: 2px solid #6CA893;\n"
"}\n"
"")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("/home/nisala/mobile_robot_ws/src/smrr_gui/smrr_gui/GUIs/Icons/highfive.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_highfive.setIcon(icon2)
        self.btn_highfive.setIconSize(QtCore.QSize(30, 30))
        self.btn_highfive.setObjectName("btn_highfive")
        self.horizontalLayout_7.addWidget(self.btn_highfive)
        self.mainstack.addWidget(self.Arm)
        self.Notifications = QtWidgets.QLabel(self.centralwidget)
        self.Notifications.setGeometry(QtCore.QRect(40, 10, 691, 51))
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.Notifications.setFont(font)
        self.Notifications.setWordWrap(True)
        self.Notifications.setObjectName("Notifications")
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setGeometry(QtCore.QRect(40, 370, 701, 81))
        self.frame_2.setMaximumSize(QtCore.QSize(16777215, 81))
        self.frame_2.setStyleSheet("/* Simple Frame Style - Overrides parent styles */\n"
"QFrame {\n"
"    background-color: #ffffff;\n"
"    border: 2px solid #00C9A7;\n"
"    border-radius: 8px;\n"
"    padding: 12px;\n"
"}\n"
"\n"
"/* Optional variations */\n"
"QFrame#specialFrame {  /* For frames with objectName=\"specialFrame\" */\n"
"    border: 3px dashed #00A8A8;\n"
"    background-color: #F8FFFF;\n"
"}\n"
"\n"
"QFrame:hover {\n"
"    border-color: #00E6D3;\n"
"    background-color: #F5FDFF;\n"
"}\n"
"\n"
"QFrame[frameShape=\"1\"] {  /* StyledPanel */\n"
"    border: 2px groove #00C9A7;\n"
"}\n"
"\n"
"QFrame[frameShape=\"4\"] {  /* WinPanel */\n"
"    border: 2px solid #00C9A7;\n"
"    background: qlineargradient(x1:0, y1:0, x2:0, y2:1,\n"
"                                stop:0 #FFFFFF, stop:1 #E0F7FA);\n"
"}")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.btn_crowdnav = QtWidgets.QPushButton(self.frame_2)
        self.btn_crowdnav.setStyleSheet("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("/home/nisala/mobile_robot_ws/src/smrr_gui/smrr_gui/GUIs/Icons/crowdnav.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_crowdnav.setIcon(icon3)
        self.btn_crowdnav.setIconSize(QtCore.QSize(30, 30))
        self.btn_crowdnav.setObjectName("btn_crowdnav")
        self.horizontalLayout_6.addWidget(self.btn_crowdnav)
        self.btn_multifloor = QtWidgets.QPushButton(self.frame_2)
        self.btn_multifloor.setStyleSheet("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("/home/nisala/mobile_robot_ws/src/smrr_gui/smrr_gui/GUIs/Icons/multifloor.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_multifloor.setIcon(icon4)
        self.btn_multifloor.setIconSize(QtCore.QSize(30, 30))
        self.btn_multifloor.setObjectName("btn_multifloor")
        self.horizontalLayout_6.addWidget(self.btn_multifloor)
        self.btn_arm = QtWidgets.QPushButton(self.frame_2)
        self.btn_arm.setMaximumSize(QtCore.QSize(227, 50))
        self.btn_arm.setStyleSheet("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("/home/nisala/mobile_robot_ws/src/smrr_gui/smrr_gui/GUIs/Icons/arm.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_arm.setIcon(icon5)
        self.btn_arm.setIconSize(QtCore.QSize(40, 40))
        self.btn_arm.setObjectName("btn_arm")
        self.horizontalLayout_6.addWidget(self.btn_arm)
        self.frame_3 = QtWidgets.QFrame(self.centralwidget)
        self.frame_3.setGeometry(QtCore.QRect(40, 70, 691, 41))
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(self.frame_3)
        self.label.setStyleSheet("font-size: 20px;\n"
"font-weight: bold;")
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.floorStack.setCurrentIndex(3)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_2.setText(_translate("MainWindow", "WELCOME"))
        self.btn_crwnav_run.setText(_translate("MainWindow", "Run"))
        self.btn_flr_G.setText(_translate("MainWindow", "Ground Floor"))
        self.btn_flr_1.setText(_translate("MainWindow", "1st Floor"))
        self.btn_flr_2.setText(_translate("MainWindow", "2nd Floor"))
        self.btn_flr_3.setText(_translate("MainWindow", "3rd Floor"))
        self.btn_reception.setText(_translate("MainWindow", "Reception"))
        self.btn_entc1.setText(_translate("MainWindow", "ENTC1"))
        self.btn_uav.setText(_translate("MainWindow", "UAV"))
        self.btn_com_lab.setText(_translate("MainWindow", "Computer lab"))
        self.btn_office.setText(_translate("MainWindow", "Office"))
        self.btn_conference.setText(_translate("MainWindow", "Conference Room"))
        self.btn_digi_lab.setText(_translate("MainWindow", "Digitab lab"))
        self.btn_analog_lab.setText(_translate("MainWindow", "Analog Lab"))
        self.btn_pg_room.setText(_translate("MainWindow", "PG Seminar Room"))
        self.btn_tele_lab.setText(_translate("MainWindow", "Telecom Lab"))
        self.Notifications_2.setText(_translate("MainWindow", "Ground Floor"))
        self.btn_ayubowan.setText(_translate("MainWindow", "Ayubowan"))
        self.btn_hi.setText(_translate("MainWindow", "Hi"))
        self.btn_highfive.setText(_translate("MainWindow", "HighFive"))
        self.Notifications.setText(_translate("MainWindow", "Notifications"))
        self.btn_crowdnav.setText(_translate("MainWindow", "Crowd Navigation"))
        self.btn_multifloor.setText(_translate("MainWindow", "Multifloor Navigation"))
        self.btn_arm.setText(_translate("MainWindow", "Arm Manipulator"))
        self.label.setText(_translate("MainWindow", "SANSAR : Mobile Robot Receptionist"))
